### ISSUE TITLE
Unable to display Films entries

### ISSUE THREAD

**Issue by woj76** [emilsvennesson/kodi-viaplay#46]
Since couple of months (should have reported this earlier), I cannot enter "Filmer" in the plug-in, the plug-in crashes with an error. All other entries work, can be displayed and videos played. I am not entirely sure if the source of the problem is in the ViaPlay API, or in the Kodi libraries (I run Kodi 9.2.7 on RaspberryPI 3), in any case, the error message from the log is this:

`2021-06-25 22:09:55.886 T:1476391680   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: '_links'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.viaplay/default.py", line 5, in <module>
                                                addon.run()
                                              File "/storage/.kodi/addons/plugin.video.viaplay/resources/lib/addon.py", line 21, in run
                                                plugin.run()
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/storage/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/storage/.kodi/addons/plugin.video.viaplay/resources/lib/addon.py", line 78, in vod
                                                helper.add_item(i['title'], plugin.url_for(list_products, url=i['_links']['self']['href']))
                                            KeyError: '_links'
                                            -->End of Python script error report<--
2021-06-25 22:09:56.244 T:1509962496   ERROR: GetDirectory - Error getting plugin://plugin.video.viaplay/vod?url=https%3a%2f%2fcontent.viaplay.se%2fxdk-se%2ffilm
2021-06-25 22:09:56.246 T:1937128896   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.viaplay/vod?url=https%3a%2f%2fcontent.viaplay.se%2fxdk-se%2ffilm) failed
`
I googled all I can and also tried to debug this a bit myself (don't really have an environment to do it properly), but no luck so far.

**Comment by zuzia-dev** [comment]
Norwegian version:

```
2021-08-07 16:22:15.241 T:140618528614144   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: '_links'
                                            Traceback (most recent call last):
                                              File "/home/zuzia/.kodi/addons/plugin.video.viaplay/default.py", line 5, in <module>
                                                addon.run()
                                              File "/home/zuzia/.kodi/addons/plugin.video.viaplay/resources/lib/addon.py", line 22, in run
                                                plugin.run()
                                              File "/home/zuzia/.kodi/addons/script.module.routing/lib/routing.py", line 130, in run
                                                self._dispatch(self.path)
                                              File "/home/zuzia/.kodi/addons/script.module.routing/lib/routing.py", line 141, in _dispatch
                                                view_func(**kwargs)
                                              File "/home/zuzia/.kodi/addons/plugin.video.viaplay/resources/lib/addon.py", line 99, in vod
                                                helper.add_item(i['title'], plugin.url_for(list_products, url=i['_links']['self']['href']))
                                            KeyError: '_links'
                                            -->End of Python script error report<--
2021-08-07 16:22:15.601 T:140618546542336   ERROR: GetDirectory - Error getting plugin://plugin.video.viaplay/vod?url=https%3a%2f%2fcontent.viaplay.no%2fxdk-no%2ffilmer
2021-08-07 16:22:15.628 T:140619269698304   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.viaplay/vod?url=https%3a%2f%2fcontent.viaplay.no%2fxdk-no%2ffilmer) failed
```

**Comment by Mariusz89B** [comment]
Here is a fix for this issue, 
https://github.com/Mariusz89B/kodi-viaplay/releases/

**Comment by zuzia-dev** [comment]
It works just fine via Kodi 18.9.  Well done, @Mariusz89B, you are great :)

**Comment by woj76** [comment]
Brief check indicates it works for me too, thanks! BTW, it seems Emil has vanished?...

**Comment by Leatherface75** [comment]
> Brief check indicates it works for me too, thanks! BTW, it seems Emil has vanished?...

I think he is too busy right now.

**Comment by Mariusz89B** [comment]
@woj76 @Leatherface75 https://github.com/emilsvennesson/kodi-viaplay/pull/50#issuecomment-896712043
